export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING'

export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING'

export const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER'

export const COMPONENT_FORM_DATA_INFLATED = 'COMPONENT_FORM_DATA_INFLATED'

export const PAGE_FIT_AREA_SETTED = 'PAGE_FIT_AREA_SETTED'

export const APP_LIST_MIGRATION = 'APP_LIST_MIGRATION'

export const MIGRATED_APP_LIST_LOADED = 'MIGRATED_APP_LIST_LOADED'

export const APP_ID_CHANGED = 'APP_ID_CHANGED'
