export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';


//09
export const LOGINNEW = 'LOGINNEW';
export const LOGINOUT = 'LOGINOUT';

export const BANNER = 'BANNER';

//首页
export const GETHOMEPAGE = 'GETHOMEPAGE';


//轮播banner的接口
export const LISTBANNER = 'LISTBANNER';
export const DELETEBANNER = 'DELETEBANNER';
export const SEARCHBINDBANNER = 'SEARCHBINDBANNER';
export const COURSEBINDBANNER = 'COURSEBINDBANNER';
export const UPLOAD = 'UPLOAD';
export const UPDATEBINDBANNER = 'UPDATEBINDBANNER';



//课程的接口
export const GETCOURSETYPE = 'GETCOURSETYPE';
export const GETFIRSTCATEGORY = 'GETFIRSTCATEGORY';
export const GETNEXTCATEGORY = 'GETNEXTCATEGORY';
export const GETCOURSE = 'GETCOURSE';
export const ADDCOURSE = 'ADDCOURSE';
export const GETCOURSECOUNT = 'GETCOURSECOUNT';
export const UPDATECOURSE = 'UPDATECOURSE';
export const DELETECOURSE = 'DELETECOURSE';
export const GETCOURSEDEFAULTPHOTO = 'GETCOURSEDEFAULTPHOTO';
export const GETCOURSEBYCOURSEID = 'GETCOURSEBYCOURSEID';
export const VALIDATECOURSE = 'VALIDATECOURSE';




//试题库
export const QUESTIONTYPELIST = 'QUESTIONTYPELIST';
export const QUESTIONPOINTLIST = 'QUESTIONPOINTLIST';
export const QUESTIONPOINTLIST2 = 'QUESTIONPOINTLIST2';
export const QUESTIONPOINTLIST3 = 'QUESTIONPOINTLIST3';


export const QUESTIONDIFFICULTYLIST = 'QUESTIONDIFFICULTYLIST';
export const QUESTIONPAGELIST = 'QUESTIONPAGELIST';
export const DELETEQUESTION = 'DELETEQUESTION';
export const ADDQUESTION = 'ADDQUESTION';
export const GETQUESTIONINFO = 'GETQUESTIONINFO';
export const ISQUESTIONEDITSTATUS = 'ISQUESTIONEDITSTATUS';


//试卷库
export const PAPERCLASSIFYLIST = 'PAPERCLASSIFYLIST';
export const GETPAPERBYPAGE = 'GETPAPERBYPAGE';  //试卷列表
export const DELETEPAPERBYID = 'DELETEPAPERBYID';  //删除
export const ADDPAPERINFO = 'ADDPAPERINFO';  //新建
export const UPDATEPAPERINFO = 'UPDATEPAPERINFO';  //编辑



//考试详情
export const GETEXAMINFOBYEXAMCONDITION = 'GETEXAMINFOBYEXAMCONDITION'; // 考试列表
export const GETEXAMDETAILINFO = 'GETEXAMDETAILINFO'; // 根据考试id查询试卷详细信息
export const DELETEEXAM = 'DELETEEXAM'; // 删除考试信息
export const VALIDATECHANGEEXAMINFO = 'VALIDATECHANGEEXAMINFO'; // 校验本次考试是否能进行编辑
export const GETEXAMTOTALCOUNTINFO = 'GETEXAMTOTALCOUNTINFO'; // 统计信息
export const GETEXAMPERSONSCORECOUNTINFO = 'GETEXAMPERSONSCORECOUNTINFO'; // 考试人员信息
export const GETCREATEBLANKPAPERINFO = 'GETCREATEBLANKPAPERINFO'; // 获取生成空白试卷需要信息
export const ADDQUESTIONPOINT = 'ADDQUESTIONPOINT'; // 添加试题知识点
export const CREATEEXAM = 'CREATEEXAM'; // 创建考试信息
export const GETQUESTIONBYPAGE = 'GETQUESTIONBYPAGE'; // 从试题库选题
export const GETEXAMDEFAULTPHOTO = 'GETEXAMDEFAULTPHOTO'; // 获取默认考试封面图片
export const GETALLGROUPINFO = 'GETALLGROUPINFO'; // 获取族群列表
export const GETPERSONINFOBYGROUPID = 'GETPERSONINFOBYGROUPID'; // 通过族群id获取指定族群人员信息
export const GETPERSONBYBLURNAME = 'GETPERSONBYBLURNAME'; // 根据考试id，人名模糊查找获取某公司某部门下人员名单
export const GETALLDEPARTMENT = 'GETALLDEPARTMENT'; // 获取公司、部门分布信息接口
export const GETISCHECKEXAMPERSON = 'GETISCHECKEXAMPERSON'; // 根据考试id获取某公司某部门下人员名单接口
export const GROUPISEXISTBYGROUPNAME = 'GROUPISEXISTBYGROUPNAME'; // 通过族群名称判断族群是否存在
export const ADDGROUP = 'ADDGROUP'; // 新增/编辑族群
export const DOWNLOADPAPERTEMPLATE = 'DOWNLOADPAPERTEMPLATE'; // 下载考试试卷EXCEL模板接口
export const GETQUSTIONSDETAILFROMBANK = 'GETQUSTIONSDETAILFROMBANK'; // 从题库获取选择题目的详细信息接口
export const GETPOINTLIST = 'GETPOINTLIST'; // 获取知识点接口
export const EMPTY_PERSON_LIST = 'emptyPersonList'










